CREATE TABLE IF NOT EXISTS service (
	id SERIAL PRIMARY KEY,
	host VARCHAR(50) NOT NULL,
	port INTEGER NOT NULL,
	description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS cpu (
	id SERIAL PRIMARY KEY,
	service_id INTEGER REFERENCES service,
	description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS cpu_temp (
	id SERIAL PRIMARY KEY,
	cpu_id INTEGER REFERENCES cpu,
	core INTEGER NOT NULL,
	value NUMERIC(15,3) NOT NULL,
	date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cpu_fan (
	id SERIAL PRIMARY KEY,
	cpu_id INTEGER REFERENCES cpu,
	speed INTEGER NOT NULL,
	date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cpu_usage (
  id SERIAL PRIMARY KEY,
  cpu_id INTEGER REFERENCES cpu,
  "user" NUMERIC(15,3) NOT NULL,
  system NUMERIC(15,3) NOT NULL,
  iowait NUMERIC(15,3) NOT NULL,
  date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS gpu (
	id SERIAL PRIMARY KEY,
	service_id INTEGER REFERENCES service,
	description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS gpu_temp (
	id SERIAL PRIMARY KEY,
	gpu_id INTEGER REFERENCES gpu,
	value NUMERIC(15,3) NOT NULL,
	date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS gpu_fan (
	id SERIAL PRIMARY KEY,
	gpu_id INTEGER REFERENCES gpu,
	speed INTEGER NOT NULL,
	date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS network_usage (
	id SERIAL PRIMARY KEY,
	service_id INTEGER REFERENCES service,
	download NUMERIC(15,3) NOT NULL,
	upload NUMERIC(15,3) NOT NULL,
	date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS disk (
	id SERIAL PRIMARY KEY,
	service_id INTEGER REFERENCES service,
	description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS partition (
	id SERIAL PRIMARY KEY,
	disk_id INTEGER REFERENCES disk,
	name VARCHAR(50) NOT NULL,
	current NUMERIC(15,3) NOT NULL,
	max NUMERIC(15,3) NOT NULL,
	date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS disk_usage (
	id SERIAL PRIMARY KEY,
	disk_id INTEGER REFERENCES disk,
	read NUMERIC(15,3) NOT NULL,
	write NUMERIC(15,3) NOT NULL,
	date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS memory_usage (
  id SERIAL PRIMARY KEY,
  service_id INTEGER REFERENCES service,
  current NUMERIC(15,3) NOT NULL,
  max NUMERIC(15,3) NOT NULL,
  date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS system_logs (
  id SERIAL PRIMARY KEY,
  service_id INTEGER REFERENCES service,
  file_path TEXT NOT NULL,
  log TEXT NOT NULL,
  file_number INTEGER NOT NULL,
  date TIMESTAMP NOT NULL
);